github:
  - 'azkadev'

custom:
  - "https://github.com/azkadev/azkadev/blob/main/assets/gopay.png"
  - "https://www.patreon.com/c/azkadev"
  - "https://opencollective.com/azkadev"
  - "https://paypal.me/azkaaxeliongibran"
  - "https://paypal.me/azkadev"